set nocompatible
filetype off

" Set the runtime path to include Vundle and initiliaze.
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Manage Vundle with Vundle.
Plugin 'gmarik/Vundle.vim'
" ---------------------------------
" Additonal Plugins installed here:
" ---------------------------------
" general syntax checker
Plugin 'scrooloose/syntastic'
" add-on to netrw browser
Plugin 'tpope/vim-vinegar'
" statusbar/tabline
Plugin 'bling/vim-airline'

call vundle#end()
filetype plugin indent on

" To use plugin indent changes, instead use:
" filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ


" ----------------------------------
" Non-Plugin configuration settings:
" ----------------------------------
" Set to support 256 colorschemes.
set t_Co=256

" Set colorscheme.
colorscheme Tomorrow-Night-Eighties
syntax on

" Add line numbers.
set number

" Set column highlight at 80 char.
set colorcolumn=80

" Set tabs to 4 spaces.
set tabstop=4
set shiftwidth=4
set expandtab

" Enable code folding.
augroup vimrc
    au BufReadPre * setlocal foldmethod=indent
    au BufWinEnter * if &fdm == 'indent' | setlocal foldmethod=manual | endif
augroup END    
set foldlevel=99

" Specify syntax checkers for Python ('flake8', 'pyflakes', 'pylint',
" 'python').
" let g:syntactic_python_checkers = ['pylint']

" vim-airline configurations.
set laststatus=2
let g:airline#extensions#tabline#enabled=1
let g:airline_powerline_fonts=1
if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif
